config/routes.rb
CSGResearchIntegrity::Application.routes.draw do
  

  resources :pages

  devise_for :admins, :path => "admin_user", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'create_account' }

  
  resources :signatories

  
  get "home/index"

  root :to => "pages#show", :id => 1;
  
  
  
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :name, :permalink, :content

  extend FriendlyId
    friendly_id :permalink

end

app/models/signatory.rb
class Signatory < ActiveRecord::Base
  
  validates_presence_of :fname, :lname, :email
  validates_uniqueness_of :email, :student_id, :student_id
  validates_format_of :email,
  :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def new
    @signatory = Signatory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @signatory }
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_filter :authenticate_admin!, :only => [:index, :new, :create, :edit, :update, :destroy]
  
  def index
    @pages = Page.all
  end

  def show
      @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      redirect_to @page, :notice => "Successfully created page."
    else
      render :action => 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
      redirect_to @page, :notice  => "Successfully updated page."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to pages_url, :notice => "Successfully destroyed page."
  end
end

app/controllers/signatories_controller.rb
class SignatoriesController < ApplicationController
  # GET /signatories
  # GET /signatories.json
  
  respond_to :html, :xml
  before_filter :authenticate_admin!, :only => [:index, :show]
  
  
  def index
    @signatories = Signatory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @signatories }
    end
  end

  # GET /signatories/1
  # GET /signatories/1.json
  
  def permalink_to(post)
    post_permalink_path(post.permalink)
  end
  
  def show
    @signatory = Signatory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @signatory }
    end
  end

  # GET /signatories/new
  # GET /signatories/new.json
  def new
    @signatory = Signatory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @signatory }
    end
  end

  # GET /signatories/1/edit
  def edit
    @signatory = Signatory.find(params[:id])
  end

  # POST /signatories
  # POST /signatories.json
  def create
    @signatory = Signatory.new(params[:signatory])

    respond_to do |format|
      if @signatory.save
        
        
        
        
        format.html { redirect_to @signatory, notice: 'Signatory was successfully created.' }
        format.json { render json: @signatory, status: :created, location: @signatory }
      else
        format.html { render action: "new" }
        format.json { render json: @signatory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /signatories/1
  # PUT /signatories/1.json
  def update
    @signatory = Signatory.find(params[:id])

    respond_to do |format|
      if @signatory.update_attributes(params[:signatory])
        format.html { redirect_to @signatory, notice: 'Signatory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @signatory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signatories/1
  # DELETE /signatories/1.json
  def destroy
    @signatory = Signatory.find(params[:id])
    @signatory.destroy

    respond_to do |format|
      format.html { redirect_to signatories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signatories_helper.rb
module SignatoriesHelper
end

app/helpers/signatory_helper.rb
module SignatoryHelper
end

app/views/home/_form.html.erb
<%= form_for @home do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.tinymce :content %>
</p>
  <p><%= f.submit %></p>
<% end %>

app/views/home/index.html.erb
<h1 class="petition_title">Take Action, Sign the Petition Today!</h1>
<h3 class="petition_title">To demand accountability and transparency</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Coal Seam Gas | Research Integrity</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>

    <%= yield(:head) %>
    <%= init_tinymce_hammer_if_required %>

    <%= analytics_init if Rails.env.production? %>

<!--Meta Tags -->
<meta name="description" content="The Research Integrity Coalition is a volunteer student organisation dedicated to
ensuring that the Centre for Coal Seam Gas at the University of Queensland, St Lucia maintains academic integrity and
transparency" />
<meta name="author" content="Research Integrity Coalition"/>
    <meta name="author" content="UQ Environment Collective"/>
    <meta name="author" content="UQ Climate for Change"/>
    <meta name="author" content="Jake Schoermer"/>
    <meta name="author" content="Abraham O'Neill"/>
    <meta name="author" content="Giovanni Sottile"/>
<meta name="keywords" content="Coal Seam Gas, CSG, Sustainable Minerals Institute, Centre for Coal Seam Gas, Chris Moran"/>
<!-- End Meta Tags -->

<!-- Favicon -->
<link rel="icon" href="/favicon.png" />
<link rel="icon" href="/favicon.ico" />
<!-- End Favicon -->

</head>
<body>
	
	
	<%if admin_signed_in?%>
		<div id="admin_bar">
			<ul class="left">
				<li class="bold">Admin Bar</li>
				<li><%= link_to "List Signatories", {:controller => "signatories", :action => "index", }%></li>
				<li><%= link_to "List Pages", {:controller => "pages", :action => "index"}%></li>
			</ul>
			<ul class="right">
				<li>
					<%= link_to("Logout", "/admin_user/logout") %>
				</li>
			</ul>
		</div>
	<%end%>


    <header>
       <div id="header-inner">
        <h1><%= link_to "Demand Coal Seam Gas Research Integrity", :controller => "pages", :action => "show", :id => "1" %></h1>
        <h2><%= link_to "@UQ", :controller => "pages", :action => "show", :id => "1" %></h2>
       </div>
    </header>

	<div id="page-wrapper">

			
		<nav>
			<ul>
				<li><%= link_to "Home", "/pages/home" %></li>
                <li><%= link_to "About CSG Extraction", "/pages/about-csg-extraction"%></li>
				<li><%= link_to "Media Coverage", "/pages/media-coverage"%></li>
                <li><%= link_to "Contact", "/pages/contact"%></li>
				<li><%= link_to "Sign the Petition", {:controller => "signatories", :action => "new"}%></li>
			</ul>
			<%= link_to image_tag("socialmedia-icons/facebook.png", :size =>"64x64", :alt => "Facebook Campaign Page", :id=>"facebook_icon"), "https://www.facebook.com/#!/CentreforCoalSeamGas"%>
		</nav>
			
		<div id="content">

		<p class="notice"><%= notice %></p>
		  <p class="alert"><%= alert %></p>
			
			<%= yield %>
		
		</div>

  </div> <!-- End #page-wrapper -->

	<footer>
		<div id="footer-inner">		
			<div id="footer-left" class="footer-section">
				<p>The Research Integrity Coalition is an initiative of the UQ Environment Collective and
				<%= link_to "UQ Climate for Change", "http://www.uqclimateforchange.org" %>.  </p>
			</div> <!--End #footer-left -->
		
			<div id="footer-middle" class="footer-section">
				<p>Site by <%= mail_to "jake@secretservers.net", "Jake Schoermer" %></p>
                <p>Content &copy; Copyright <%= Date.current.to_s[0...4] %> Research Integrity Coalition </p>
                <%if !admin_signed_in?%>
                        <%= link_to 'Admin Logon', "/admin_user/login" %>
               	<%end%>

			</div> <!-- End #footer-middle-->
			<div id ="footer-right" class="footer-section">
				<%= image_tag "uqenvirocollective-logo-small.png", size:"80x80"%>
				<%= image_tag "uqcfc-logo-b&w-small.png", size:"80x80"%>
			</div> <!-- End #footer-right-->
		</div> <!-- End #footer-inner-->
	</footer>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.tinymce :content %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/pages/edit.html.erb
<% title "Edit Page" %>

<%= render 'form' %>
<p>
  <%= link_to "Show", @page %> |
  <%= link_to "View All", pages_path %>
</p>

app/views/pages/index.html.erb
<% title "Pages" %>

<table>
  <tr>
    <th>Name</th>
    <th>Permalink</th>
    <th>Content</th>
  </tr>
  <% for page in @pages %>
    <tr>
      <td><%= page.name %></td>
      <td><%= page.permalink %></td>
      <td><%= raw(page.content)[0..300]+"..." %></td>
      <td><%= link_to "Show", page %></td>
      <td><%= link_to "Edit", edit_page_path(page) %></td>
      <td><%= link_to "Destroy", page, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Page", new_page_path %></p>

app/views/pages/new.html.erb
<% title "New Page" %>

<%= render 'form' %>

<p><%= link_to "Back to List", pages_path %></p>

app/views/pages/show.html.erb
<% title @page.name %>


<!-- Show Content -->
<%=raw @page.content %>


<%if admin_signed_in?%>
<p>
  <%= link_to "Edit", edit_page_path(@page) %> |
  <%= link_to "Destroy", @page, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", pages_path %>
</p>
<%end%>

app/views/signatories/_form.html.erb
<%= form_for(@signatory) do |f| %>
  <% if @signatory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signatory.errors.count, "error") %> prohibited this signatory from being saved:</h2>

      <ul>
      <% @signatory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "First Name" %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label "Last Name" %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
  <label>ID</label><br />
  <%= f.text_field :student_id %><br />
  <sub>Your UQ Staff or Student ID (if Applicable)</sub>

  </div>
  <div class="field">
    <%= f.label :affiliation %><br />
    <%= select_tag "signatory[affiliation]", "<option value='UNDERGRAD'>UQ Undergrad</option><option value='POSTGRAD'>
    UQ Postgrad</option><option value='STAFF'>UQ Staff Member</option><option value='OTHER'>Non-UQ</option>".html_safe%>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= submit_tag "Sign the Petition" %>
  </div>
<% end %>

app/views/signatories/edit.html.erb
<h1>Editing signatory</h1>

<%= render 'form' %>

<%= link_to 'Show', @signatory %> |
<%= link_to 'Back', signatories_path %>

app/views/signatories/index.html.erb
<h1 class>List of Signatories</h1>

<p>Below is the complete list of those who have currently signed the Research Integrity petition.</p>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Student ID</th>
    <th>Affiliation</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signatories.each do |signatory| %>
  <tr>
    <td><%= signatory.fname %></td>
    <td><%= signatory.lname %></td>
    <td><%= signatory.email %></td>
    <td><%= signatory.student_id %></td>
    <td><%= signatory.affiliation%></td>
    <td><%= signatory.message %></td>
    <td><%= link_to 'Show', signatory %></td>
    <td><%= link_to 'Edit', edit_signatory_path(signatory) %></td>
    <td><%= link_to 'Destroy', signatory, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Signatory', new_signatory_path %>

app/views/signatories/new.html.erb
<h1 class="petition_title center">Take Action, Sign the Petition Today!</h1>
<h3 class="petition_title center">To demand accountability and transparency</h3>

<%= render 'form' %>

app/views/signatories/save.html.erb
<h1>Test</h1>

app/views/signatories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> fname:</b>
  <%= @signatory. fname %>
</p>

<p>
  <b>Lname:</b>
  <%= @signatory.lname %>
</p>

<p>
  <b>Email:</b>
  <%= @signatory.email %>
</p>

<p>
  <b>Student:</b>
  <%= @signatory.student_id %>
</p>

<p>
  <b>:</b>
  <%= @signatory.affiliation %>
</p>

<p>
  <b>Message:</b>
  <%= @signatory.message %>
</p>


<%= link_to 'Edit', edit_signatory_path(@signatory) %> |
<%= link_to 'Back', signatories_path %>